gpu_list:
    - 1
seed: 123
dump_path: '/fast_scratch/lcook/WCTE_mu_scatter_class/CustMuonScatter_linE/output'
defaults:
    - data: wcte
    - data/dataset: wcte_cnn
    - model: classifier
    - model/feature_extractor: resnet18
    - model/classification_network: resnet
    - engine: classifier
    - tasks/train: train_resnet
    - optimizers@tasks.train.optimizers: adam
    - loss@tasks.train.loss: cross_entropy
    - sampler@tasks.train.data_loaders.train.sampler: subset_random
    - sampler@tasks.train.data_loaders.validation.sampler: subset_random
    - tasks/restore_best_state: restore_best_state
    - tasks/evaluate: test
    - sampler@tasks.evaluate.data_loaders.test.sampler: subset_sequential
    - _self_
